### ISSUE TITLE
Call to nonexistent Function Error

### ISSUE THREAD

**Issue by SuganthanBC** [joeyespo/autohotkey-scripts#1]
While I compile this script, It shows Call to nonexistent Function Error
at Line : #If MouseIsOver("ahk_class Shell_TrayWnd")
Should I update my Library ? or just Include anything ?

**Comment by joeyespo** [comment]
What version of AHK are you running?

**Comment by SuganthanBC** [comment]
AutoHotkey v1.1.13.01

**Comment by joeyespo** [comment]
Ok. I'm still on v1.1.10.1.

Looks like it's an AHK bug. [Here's a thread on the same issue](http://www.autohotkey.com/board/topic/83344-problem-with-if-when-i-compile-a-script/). They provide a temporary fix in there. See if that'll work for you.
